spring:
  application:
    name: Person Data Service

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: interviewDB
      username: admin
      password: admin
      database: interviewDB

logging.file: application.log
logging:
  max-history: 5
  max-size: 100MB
  pattern:
    file: "%date{ISO8601} thread=%thread service=${springAppName:-} pid=${PID:-} trace=%X{X-B3-TraceId:-} span=%X{X-B3-SpanId:-} parent=%X{X-B3-ParentSpanId:-} logLevel=%level class=%logger{40} %msg%n"
  level:
    org.springframework.security: INFO
    com.aid.interview: INFO